### ISSUE TITLE
Trainer does not expect keyword argument 'gpus'

### ISSUE THREAD

**Issue by joelmeyerson** [aqlaboratory/genie#1]
Hi Mohammed and Yeqing, this is really exciting work! Thanks for sharing the code and providing nice documentation. I encountered a very minor issue running it which I thought I'd mention.

To install Genie I created a fresh `venv` and installed the dependencies using `pip install -e .`. I then downloaded and cleaned the SCOPe dataset as instructed in the README, and created a sub-directory in `runs` and a configuration file. I then started training but got an error. Here's the stack trace:

```
Traceback (most recent call last):
  File "/home/joel/git/genie/genie/train.py", line 70, in <module>
    main(args)
  File "/home/joel/git/genie/genie/train.py", line 44, in main
    trainer = Trainer(
  File "/home/joel/git/genie/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: Trainer.__init__() got an unexpected keyword argument 'gpus'
```
I believe the source of the issue is that pip installed `v2.0.1` of PyTorch Lightning and according to [this discussion](https://github.com/Lightning-AI/lightning/issues/11902) `Trainer` may now expect the keyword arguments `devices` and `accelerator` instead of `gpus`. I was able to start training by replacing this [line](https://github.com/aqlaboratory/genie/blob/main/genie/train.py#L45) with these lines:

```
devices=gpus,
accelerator='gpu',
```

Is this issue reproducible on your end? If the issue is indeed genuine I'd be glad to submit a PR to fix it.

**Comment by yeqinglin** [comment]
Thanks for pointing this out. As you mentioned, the issue arises due to different PyTorch Lightning version. In the latest version of PyTorch Lightning, the above modification would fix the issue.

**Comment by joelmeyerson** [comment]
Thanks. I created a PR that will fix the issue.
